### ISSUE TITLE
Using addon

### ISSUE THREAD

**Issue by princessayushi** [webgroup-limited/id.net-construct-sdk#2]
Hi , I am having trouble in using this addon . I am using construct 3 , I assume c3 port should work . There is no c3 addon file provided. How should it work with c3 ? I have always imported c3 addon from addon manager. Kindly help . I can use it with construct 2 ,if needed.

**Comment by EddieOne** [comment]
Hello, We tried to port the plugin automatically but I believe they removed the c2 engine from c3. We will need to create a c3 plugin. Some have begun implementing the JS APIs using JavaScript.

**Comment by EddieOne** [comment]
https://github.com/webgroup-limited/y8-construct3-sdk
